// Generated by CoffeeScript 1.9.1
define(function(require, exports, module) {
  "use strict";
  var Engine, Home, RotateRectView, mainContext;
  Engine = require("famous/core/Engine");
  RotateRectView = require("module/rotateRectView");
  mainContext = Engine.createContext();
  mainContext.setPerspective(1000);
  Home = {};
  Home.init = function() {
    var view1, view2, view3;
    view1 = new RotateRectView({
      align: [0.3, 0.3],
      origin: [0.3, 0.3],
      size: [200, 200],
      frequency: 2
    });
    view2 = new RotateRectView({
      align: [0.7, 0.7],
      origin: [0.7, 0.7],
      size: [100, 100],
      frequency: 4,
      color: "#7EDC7B"
    });
    view3 = new RotateRectView({
      align: [0.3, 0.7],
      origin: [0.3, 0.7],
      size: [120, 80],
      frequency: 0.5,
      color: "black"
    });
    mainContext.add(view1);
    mainContext.add(view2);
    return mainContext.add(view3);
  };
  return module.exports = Home;
});
