// Generated by CoffeeScript 1.9.1
define(function(require, exports, module) {
  "use strict";
  var Modifier, RotateRect, Surface, Transform;
  Modifier = require('famous/core/Modifier');
  Transform = require('famous/core/Transform');
  Surface = require('famous/core/Surface');
  RotateRect = (function() {
    function RotateRect(config) {
      if (config == null) {
        config = {};
      }
      this.position = config.position != null ? config.position : {
        align: [0.5, 0.5],
        origin: [0.5, 0.5]
      };
      this.size = config.size != null ? config.size : [200, 200];
      this.color = config.color != null ? config.color : "#FA5C4F";
      this.frequency = config.frequency != null ? config.frequency : 2;
    }

    RotateRect.prototype.init = function(mainContext) {
      var _$, centerSpinModifier, initialTime, rectSurface;
      _$ = this;
      rectSurface = new Surface({
        size: _$.size,
        properties: {
          backgroundColor: _$.color
        },
        classes: ['backfaceVisibility']
      });
      initialTime = Date.now();
      centerSpinModifier = new Modifier({
        align: _$.position.align,
        origin: _$.position.origin,
        transform: function() {
          return Transform.rotateY(_$.frequency * 0.001 * (Date.now() - initialTime));
        }
      });
      return mainContext.add(centerSpinModifier).add(rectSurface);
    };

    return RotateRect;

  })();
  return module.exports = RotateRect;
});
